name: weatherly
description: "A beautiful weather forecasting app with dynamic themes and animations"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

  # UI and Animation
  flutter_animate: ^4.5.0
  glass_kit: ^4.0.2
  cached_network_image: ^3.4.1
  
  # Localization and Formatting
  intl: ^0.20.2
  
  # Storage and Preferences
  shared_preferences: ^2.3.2
  
  # Location Services
  geolocator: ^10.1.1
  geocoding: ^4.0.0
  
  # Network Requests
  http: ^1.2.2
  
  # Notifications
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.4
  permission_handler: ^11.4.0
  
  # Utilities
  url_launcher: ^6.3.1
  connectivity_plus: ^7.0.0
  device_info_plus: ^12.1.0
  package_info_plus: ^8.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Linting
  flutter_lints: ^6.0.0
  
  # App Icon Generation
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  # Only include assets that exist
  # assets:
  #   - assets/images/
  #   - assets/icon/
  #   - assets/fonts/

  # Fonts (commented out until you add font files)
  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter-Regular.ttf
  #         weight: 400
  #       - asset: assets/fonts/Inter-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Inter-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Inter-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/Inter-ExtraBold.ttf
  #         weight: 800